### ISSUE TITLE
[Feature Request] Ability to combine several animations

### ISSUE THREAD

**Issue by SushiWaUmai** [new-data-services/tailwindcss-animated#1]
Does this library offer the ability to combine several animations?

**Comment by heidkaemper** [comment]
Not yet. And I'm not sure what the class syntax should look like with multiple animations. Do you have any idea about this?

**Comment by SushiWaUmai** [comment]
I thought of applying multiple animation classes on one element. Is that not possible?

**Comment by SushiWaUmai** [comment]
I actually thought of having multiple effects being applied at the same time, but I think that is also another missing feature

**Comment by heidkaemper** [comment]
Okay, got it. The easiest way to combine (or chain) animations would be nesting:

```
<div class="animate-spin">
  <div class="animate-jump animate-infinite">
    ...
  </div>
</div>
```

And of course you can always extend your `tailwind.config.js` and define custom animations.

I honestly don't see any other way. Multiple animations with several parameters (sequential, simultaneous, with delay, and so on..) would increase the complexity a lot. And we try to keep this plugin as simple and understandable as possible.
