### ISSUE TITLE
Change default animation duration

### ISSUE THREAD

**Issue by rcoopr** [new-data-services/tailwindcss-animated#10]
Would it be possible to add a way to change the default duration? It seems all the `animate-*` classes are hard coded with 1s duration and require an additional class to change.

It could be done with a css variable, and `animate-duration-*` would overwrite that variable

**Comment by heidkaemper** [comment]
FYI, with v1.1.0 this plugin uses custom properties for almost all utilities. That enables you to do something like:

```
<body class="animate-duration-200">
  <div class="animate-bounce"></div>
  <div class="animate-spin"></div>
</body>
```

Both animations will have a duration of 200ms.
