### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by chemiadel** [new-data-services/tailwindcss-animated#13]
how to use this plugin on CDN ?

**Comment by heidkaemper** [comment]
I don't think 3rd party plugins are currently supported by the Play CDN.

That would be a nice option to have for rapid development and experiments. However, as the Tailwind CDN is not intended for production, I think this is acceptable.

**Comment by chemiadel** [comment]
Check this out, https://jsfiddle.net/fcv5epma/

we can set theme and configs using tailwindcss config
https://tailwindcss.com/docs/installation/play-cdn

it can be useful for iframes and web builders.

Thanks

**Comment by heidkaemper** [comment]
Fair, predefined animations (keyframes) would work that way. But custom utilities not, right? Try to add a `animate-duration-75` class for example. This kind of extension only works with plugins, as far as I know.
