### ISSUE TITLE
Problem with animation-[] arbitrary values since 1.1.0

### ISSUE THREAD

**Issue by ThibautRoe** [new-data-services/tailwindcss-animated#19]
Hi,

Until 1.0.1, arbitrary values like animate-[wiggle_1s_ease-in-out_infinite] seemed to be interpreted by Tailwind directly and not by tailwindcss-animated and everything worked fine, even for custom CSS animations (animate-[myCustomAnimation_1s_ease-in-out_infinite] for example).

See https://tailwindcss.com/docs/animation#arbitrary-values (section "Arbitrary Values" at the bottom) if needed.

Since 1.1.0 and also on 1.1.1, this is broken and results in the following warning:
"warn - The class `animate-[wiggle_1s_ease-in-out_infinite]` is ambiguous and matches multiple utilities."

Am I doing something wrong or did a bug appeared since 1.0.1?

**Comment by heidkaemper** [comment]
This should be fixed with v1.1.2
https://github.com/new-data-services/tailwindcss-animated/releases/tag/v1.1.2

**Comment by ThibautRoe** [comment]
> This should be fixed with v1.1.2 https://github.com/new-data-services/tailwindcss-animated/releases/tag/v1.1.2

Everything is working fine now, thanks for the reactivity and thanks for this amazing tool.
