### ISSUE TITLE
How to integrate with React

### ISSUE THREAD

**Issue by franklamothe** [new-data-services/tailwindcss-animated#4]
I'm having an issue. Is there a way to use this in a React project? I can only use the hover state, not play animations. Animations will start right away, it needs to start only when scrolling to viewport.

**Comment by SbleitZ** [comment]
reply

**Comment by heidkaemper** [comment]
I think there is a misunderstanding about what this package does (and does not).

This package extends the default animation properties of Tailwind. That's pure CSS.
It **doesn't** come with an Intersection Observer or Scoll Listener. These would be necessary to execute animations only when an element comes into the viewport.

That being said, you surely could combine it with something like my Tailwind Intersection Package. ;-)
https://github.com/heidkaemper/tailwindcss-intersect

**Comment by tomredman** [comment]
For anybody looking for a copy & paste answer, you can do something like this:


https://github.com/new-data-services/tailwindcss-animated/assets/4225378/ad96f204-09f3-408e-bd66-0db66d632a64


```typescript
// some React component
const [scrollY, setScrollY] = useState(0);
const [animateIn, setAnimateIn] = useState(false);
const SCROLL_THRESHOLD = 135;

useEffect(() => {
  const onScroll = () => setScrollY(window.scrollY);
  window.removeEventListener("scroll", onScroll);
  window.addEventListener("scroll", onScroll, { passive: true });
  return () => window.removeEventListener("scroll", onScroll);
}, []);

useEffect(() => {
  const animate = () => {
    if (scrollY >= SCROLL_THRESHOLD) {
      setAnimateIn(true);
    } else {
      setAnimateIn(false);
    }
  };
  animate();
}, [scrollY]);

// rendering with "key" to trigger React to re-render when the class changes:

<h1
  key={animateIn ? "animate-in" : "animate-out"}
  className={cn(
    "font-header text-2xl md:text-3xl mb-2",
    animateIn
      ? "animate-fade-up animate-duration-[350ms] animate-fill-forwards animate-play"
      : "animate-fade-up animate-duration-[350ms] animate-fill-forwards animate-reverse"
  )}
>
  I fade in and out at 135px scroll.
</h1>
```
