### ISSUE TITLE
Additional Properties For Animation

### ISSUE THREAD

**Issue by bitcooker** [new-data-services/tailwindcss-animated#5]
It'd be great if we can control more properties other than timing, easing and direction.
e.x. How can I set the initial position in ``fade-down`` animation?

Each animation would have unique properties such as initial position, rotation, counts, ...

**Comment by heidkaemper** [comment]
With v1.1.0 this plugin now supports [animation-composition utilities](https://github.com/new-data-services/tailwindcss-animated?tab=readme-ov-file#can-keyframes-and-offset-values-be-changed). With these we have a bit more control over intial values and offsets.
