### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by juanCortelezzi** [new-data-services/tailwindcss-animated#6]
Hi there! Is there any chance to get type definitions?

I'm using a `tailwind.config.ts` for my project and I would love to be able to import the library without typescript crying about the import not having type definitions.

**Comment by adlerweb3** [comment]
Same problem!

### Workaround:
Necessary to make TailwindCSS-animated work with TypeScript adding the following of the file index.d.ts in node_modules/tailwindcss-animated folder:

``` index.d.ts

declare const plugin: { handler: () => void }
export = plugin

```
