### ISSUE TITLE
translateY and offsets

### ISSUE THREAD

**Issue by merijnponzo** [new-data-services/tailwindcss-animated#9]
Hi based on your theme.js within the src directory i think for example:
```
'fade-down': {
            '0%': {
                opacity: '0',
                transform: 'translateY(-2rem)',
            },
            '100%': {
                opacity: '1',
                transform: 'translateY(0)',
            },
        },
```
would not respect the original translateY value i guess like:
```
<div class="animate-fade-up w-20 h-20 translate-y-20 bg-slate-200 ">
```       
you could add a utility class (offset.js)
```
module.exports = function ({ addUtilities, matchUtilities, theme }) {
const animateUtilities = matchUtilities(
    {
        'animate-y': (value) => {
            const spacingValue = theme('spacing')[value];
            const className = `animate-y-${value}`;

            return {
                [`--an-translate-y-${value}`]: spacingValue,
            };
        },
    },
    {
        values: Object.keys(theme('spacing')),
    }
)
}
```
then change theme.js to :
```
'fade-up': {
            '0%': {
                opacity: '0',
                transform: 'translateY(var(--an-translate-y))',
            },
            '100%': {
                opacity: '1',
                transform: 'translateY(var(--tw-translate-y))',
            },
        },
```
now the div slides from your new offset position class like (animate-y-40) to the orinal y value:
```
<div class="animate-fade-up w-20 h-20 translate-y-20 bg-slate-200 animate-y-40">
```

**Comment by e10a** [comment]
Great work! I just wish there was a built-in way to use arbitrary values for more properties including offset positions.

**Comment by heidkaemper** [comment]
@merijnponzo Sorry for the late reply. But indeed a good suggestion! We'll have a look what's possible.

**Comment by heidkaemper** [comment]
With v1.1.0 this plugin now supports [animation-composition utilities](https://github.com/new-data-services/tailwindcss-animated?tab=readme-ov-file#can-keyframes-and-offset-values-be-changed). With these we have a bit more control over intial values and offsets.
